spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG
